spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?serverTimezone=Asia/Seoul
    username: root
    password: tmdghks2060@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
